// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * EmailService persists SMTP settings to disk and can send a real test
 * email using them.
 * 
 * Register it in main.go:
 * 
 * 	Services: []application.Service{
 * 	    application.NewService(&EmailService{}),
 * 	}
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * LoadSettings returns the last saved settings, or a zero-value struct if
 * nothing has been saved yet. Call this from the frontend on mount.
 * @returns {$CancellablePromise<$models.EmailSettings>}
 */
export function LoadSettings() {
    return $Call.ByID(1584582240).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * SaveSettings validates and persists the settings to disk.
 * 
 * Note: SenderPassword is stored as plaintext JSON on disk for now. For
 * production use, swap this for OS keychain storage (e.g.
 * github.com/zalando/go-keyring) instead of a plain file.
 * @param {$models.EmailSettings} settings
 * @returns {$CancellablePromise<void>}
 */
export function SaveSettings(settings) {
    return $Call.ByID(4074345785, settings);
}

/**
 * SendTestEmail validates the settings, connects to the SMTP server, and
 * sends a real test email to ReceiverEmail. Supports plain SMTP (25),
 * STARTTLS (e.g. 587), and implicit TLS (465).
 * @param {$models.EmailSettings} settings
 * @returns {$CancellablePromise<void>}
 */
export function SendTestEmail(settings) {
    return $Call.ByID(618198261, settings);
}

// Private type creation functions
const $$createType0 = $models.EmailSettings.createFrom;
