// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * EmailSettings mirrors the fields on the Email Settings page.
 */
export class EmailSettings {
    /**
     * Creates a new EmailSettings instance.
     * @param {Partial<EmailSettings>} [$$source = {}] - The source object to create the EmailSettings.
     */
    constructor($$source = {}) {
        if (!("smtpPort" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["smtpPort"] = "";
        }
        if (!("smtpServer" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["smtpServer"] = "";
        }
        if (!("senderEmail" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["senderEmail"] = "";
        }
        if (!("senderPassword" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["senderPassword"] = "";
        }
        if (!("receiverEmail" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["receiverEmail"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EmailSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EmailSettings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EmailSettings(/** @type {Partial<EmailSettings>} */($$parsedSource));
    }
}
